### ISSUE TITLE
Unable to add Ember Mug

### ISSUE THREAD

**Issue by jddayley** [sopelj/hass-ember-mug-component#4]
I'm using the latest version and the UI setup finds my ember mug.   I able to complete the setup and indicates it was successful.  However no entity is created.  Below are the debug logs.

2022-01-15 11:01:52 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ember_mug
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/ember_mug/sensor.py", line 69, in device_info
    return self.coordinator.device_info
  File "/config/custom_components/ember_mug/__init__.py", line 99, in device_info
    name=self.data["name"],
TypeError: 'NoneType' object is not subscriptable
2022-01-15 11:01:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ember_mug platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/ember_mug/sensor.py", line 69, in device_info
    return self.coordinator.device_info
  File "/config/custom_components/ember_mug/__init__.py", line 99, in device_info
    name=self.data["name"],
TypeError: 'NoneType' object is not subscriptable
2022-01-15 11:01:52 ERROR (MainThread) [custom_components.ember_mug.mug] Init: [org.freedesktop.DBus.Error.NoReply] Message recipient disconnected from message bus without replying on attempt 1. waiting 30sec

**Comment by sopelj** [comment]
Hey, yeah, sorry that was stupid error. 

I was creating a ton a versions yesterday because it was easiest to do my tests.
I'm glad creating via the UI worked for you though!

This error is fixed I just hadn't created another release. I just created `0.2.1-alpha-7` now. It fixes this error and a few others.
If you upgrade to the latest and restart home assistant you should have the sensors appear.

It will probably change a bit before release though, but It is more stable now and it correctly creates a Mug, Battery, Target temp and Current temp sensors.

**Comment by jddayley** [comment]
Thank you so much.  In the UI, it indicates "MAC address is invalid"

2022-01-15 11:53:04 ERROR (SyncWorker_1) [switchbot] Error scanning for switchbot devices
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 147, in discover
    devices = bluepy.btle.Scanner(self._interface).scan(
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 853, in scan
    self.process(timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 829, in process
    self._mgmtCmd(self._cmd())
<img width="394" alt="Screen Shot 2022-01-15 at 11 53 26 AM" src="https://user-images.githubusercontent.com/29357870/149630548-6cb7e50e-52d6-44c7-b9cf-667273ef47c5.png">
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scan'
2022-01-15 11:53:04 INFO (MainThread) [custom_components.ember_mug.mug] Found device: Ember Ceramic Mug (C6:0E:6F:D8:CD:FC)
2022-01-15 11:53:04 INFO (MainThread) [custom_components.ember_mug] {'C6:0E:6F:D8:CD:FC': 'Ember Ceramic Mug'}

**Comment by sopelj** [comment]
Oh, sorry. I haven't had a chance to re-test the config flow. Thecheck for the mac address has changed. Should work now in `0.2.1-alpha-8`, but haven't had time to test yet.

**Comment by jddayley** [comment]
Appreciate everything.   Really close.

2022-01-15 12:23:05 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:05 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:23:11 ERROR (MainThread) [custom_components.ember_mug.mug] Init: Device with address XX:XX:XX:XX:XX:XX was not found. on attempt 4. waiting 30sec
2022-01-15 12:23:15 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:15 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:23:25 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:25 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:23:35 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:35 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:23:40 INFO (MainThread) [custom_components.ember_mug] {}
2022-01-15 12:23:45 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:45 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:23:48 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsps://stream-uc2-charlie.dropcam.com:443/sdm_live_stream/CiUA2vuxr5TnFSha1p0qRCqmPfJYd9vBkXKz_mA4YkYy2P8XJnNxEnEAYm9dx1HAbCOt74Uh7g3-KbkvzqWZLVik-id86Ac7HrJuMV7HZcgMrDFqOB3BGb4k1lULZ10wPLTBR10wlmq3SRquKxL1ErydBCIHYenFLZlPR1bewJbUXVH_FKYosj58lldTsw5a-ANBVWOIEBKKkQ?auth=****
2022-01-15 12:23:52 ERROR (MainThread) [custom_components.ember_mug.mug] Init: Device with address XX:XX:XX:XX:XX:XX was not found. on attempt 5. waiting 30sec
2022-01-15 12:23:59 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:23:59 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:24:00 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://****:****@192.168.0.125/live
2022-01-15 12:24:04 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:24:04 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:24:11 INFO (MainThread) [custom_components.ember_mug] {}
2022-01-15 12:24:14 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:24:14 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:24:24 ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
2022-01-15 12:24:24 INFO (MainThread) [custom_components.ember_mug] Starting mug loop XX:XX:XX:XX:XX:XX
2022-01-15 12:24:28 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsps://stream-uc2-charlie.dropcam.com:443/sdm_live_stream/CiUA2vuxr5TnFSha1p0qRCqmPfJYd9vBkXKz_mA4YkYy2P8XJnNxEnEAYm9dx1HAbCOt74Uh7g3-KbkvzqWZLVik-id86Ac7HrJuMV7HZcgMrDFqOB3BGb4k1lULZ10wPLTBR10wlmq3SRquKxL1ErydBCIHYenFLZlPR1bewJbUXVH_FKYosj58lldTsw5a-ANBVWOIEBKKkQ?auth=****
2022-01-15 12:24:30 INFO (MainThread) [custom_components.ember_mug.mug] Connected to XX:XX:XX:XX:XX:XX
2022-01-15 12:24:30 INFO (MainThread) [custom_components.ember_mug.mug] Try to subscribe to Push Events
2022-01-15 12:24:30 INFO (MainThread) [custom_components.ember_mug.mug] Found device: Ember Ceramic Mug (XX:XX:XX:XX:XX:XX)
2022-01-15 12:24:30 INFO (MainThread) [custom_components.ember_mug] {'XX:XX:XX:XX:XX:XX': 'Ember Ceramic Mug'}
2022-01-15 12:24:32 DEBUG (MainThread) [custom_components.ember_mug.mug] Current temp 137.01
2022-01-15 12:24:33 INFO (MainThread) [custom_components.ember_mug.mug] Connected to XX:XX:XX:XX:XX:XX
2022-01-15 12:24:34 INFO (MainThread) [custom_components.ember_mug.mug] Try to subscribe to Push Events
2022-01-15 12:24:34 INFO (MainThread) [custom_components.ember_mug.mug] Push event received from Mug (5)
2022-01-15 12:24:35 DEBUG (MainThread) [custom_components.ember_mug.mug] Temperature unit from mug: bytearray(b'\x01')
2022-01-15 12:24:35 INFO (MainThread) [custom_components.ember_mug.mug] Push event received from Mug (5)
2022-01-15 12:24:36 DEBUG (MainThread) [custom_components.ember_mug.mug] Battery is at 69.0. On base: False
2022-01-15 12:24:36 DEBUG (MainThread) [custom_components.ember_mug.mug] Current temp None
2022-01-15 12:24:36 DEBUG (MainThread) [custom_components.ember_mug.mug] Liquid level now: 5
2022-01-15 12:24:37 DEBUG (MainThread) [custom_components.ember_mug.mug] Target temp None
2022-01-15 12:24:38 DEBUG (MainThread) [custom_components.ember_mug.mug] Temperature unit from mug: bytearray(b'\x01')
2022-01-15 12:24:39 DEBUG (MainThread) [custom_components.ember_mug.mug] Battery is at 69.0. On base: False
2022-01-15 12:24:40 DEBUG (MainThread) [custom_components.ember_mug.mug] Liquid level now: None
2022-01-15 12:24:43 DEBUG (MainThread) [custom_components.ember_mug] {'mug_id': 'xg5v2M38PT09', 'serial_number': 'BBG10200270', 'last_read_time': datetime.datetime(2022, 1, 15, 17, 24, 43, 731533, tzinfo=datetime.timezone.utc), 'firmware_info': {'version': 393, 'hardware': 10, 'bootloader': 0}, 'mug_name': 'Ember Ceramic Mug', 'model': 'Ember Ceramic Mug'}
2022-01-15 12:24:43 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching Ember Ceramic Mug data in 0.000 seconds (success: True)
2022-01-15 12:24:45 DEBUG (MainThread) [custom_components.ember_mug] {'mug_id': 'xg5v2M38PT09', 'serial_number': 'BBG10200270', 'last_read_time': datetime.datetime(2022, 1, 15, 17, 24, 45, 715761, tzinfo=datetime.timezone.utc), 'firmware_info': {'version': 393, 'hardware': 10, 'bootloader': 0}, 'mug_name': 'Ember Ceramic Mug', 'model': 'Ember Ceramic Mug'}
2022-01-15 12:24:45 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching Ember Ceramic Mug data in 0.000 seconds (success: True)
2022-01-15 12:24:52 ERROR (MainThread) [custom_components.ember_mug] Bleak Error whilst connecting: Device with address XX:XX:XX:XX:XX:XX was not found.
2022-01-15 12:25:00 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsps://stream-uc2-charlie.dropcam.com:443/sdm_live_stream/CiUA2vuxr5TnFSha1p0qRCqmPfJYd9vBkXKz_mA4YkYy2P8XJnNxEnEAYm9dx1HAbCOt74Uh7g3-KbkvzqWZLVik-id86Ac7HrJuMV7HZcgMrDFqOB3BGb4k1lULZ10wPLTBR10wlmq3SRquKxL1ErydBCIHYenFLZlPR1bewJbUXVH_FKYosj58lldTsw5a-ANBVWOIEBKKkQ?auth=****
2022-01-15 12:25:02 INFO (MainThread) [custom_components.ember_mug] {}

**Comment by sopelj** [comment]
Ok, I see a couple errors. Bluetooth is not the most reliable protocol and the mug is a bit finicky. I can sometimes fail to update and reconnect. Did it create any sensors? If you go into "Configuration -> Devices and Services" and check under "Ember Mug"
I do not believe the `stream_worker` errors you have are related to the mug.

**Comment by jddayley** [comment]
Appreciate all the changes today.  It works great.

**Comment by sopelj** [comment]
Awesome! I'm glad it can be useful to someone.
I suppose I'll close this issue since the original problem was fixed yesterday with [this commit](https://github.com/sopelj/hass-ember-mug-component/commit/341b3b05ff9e8e53e74f6c3923a091071a5d6a46). However don't hesitate to open another issue if you have problems or suggestions in future. I'll try and get a stable update out in the next couple days.
