### ISSUE TITLE
Travel Mug 2+ Unable to Connect (HA with ESPHome)

### ISSUE THREAD

**Issue by walk0080** [sopelj/hass-ember-mug-component#61]
* Home Assistant Version (eg. 2023.11): Core 2024.11.1 | Front End 20241106.2 (running in Docker)
* Ember Mug Component Version (eg. 0.8.0): 1.2.0-beta-3
* Which device(s) are you using for Bluetooth (e.g. Bluetooth Dongle / ESPHome Proxy): ESPHome Proxy
* Ember Mug Firmware version: 47/47

### Description

Device connected via the Integration, but I could not write (forgot to pair with iOS app first)... so factory reset the mug and followed the correct process... But now getting errors from the Integration and it will not work correctly. This is a warranty replacement mug that I just received. The original mug is still working fine for the last year or so with the HA Ember HACS Integration and ESP Home. Any help is much appreciated.

### What I Did

Added via Integration without first pairing in iOS app... connected but unable to write.
Factory reset mug and followed correct process, but now Integration fails.
Restarted ESPHome devices
Updated ESPHome device (that Mug is trying to connect to) to latest version.
Re-installed Ember Integration via HACS.
Restarted Home Assistant.

### Logs / Errors

**ESPHome Log:**
```
[14:03:55][D][esp32_ble_client:110]: [0] [C6:FC:A9:1A:E1:01] ESP_GATTC_NOTIFY_EVT
[14:03:55][D][esp32_ble_client:110]: [0] [C6:FC:A9:1A:E1:01] ESP_GATTC_NOTIFY_EVT
[14:03:57][D][esp32_ble_client:306]: [0] [C6:FC:A9:1A:E1:01] Event 39
[14:03:57][I][esp32_ble_client:084]: [0] [C6:FC:A9:1A:E1:01] Disconnecting.
[14:03:57][D][esp-idf:000][BTU_TASK]: W (602601) BT_HCI: hci cmd send: disconnect: hdl 0x0, rsn:0x13
[14:03:57][D][esp-idf:000][BTU_TASK]: W (602605) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x16
[14:03:57][D][esp-idf:000][BTU_TASK]: W (602608) BT_APPL: gattc_conn_cb: if=4 st=0 id=4 rsn=0x16
[14:03:57][D][esp-idf:000][BTU_TASK]: W (602615) BT_APPL: gattc_conn_cb: if=5 st=0 id=5 rsn=0x16
[14:03:57][D][esp32_ble_client:110]: [0] [C6:FC:A9:1A:E1:01] ESP_GATTC_CLOSE_EVT
[14:03:57][D][esp-idf:000][BTU_TASK]: W (602657) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x16
```

**Home Assistant Logs:**
```
Ember Travel Mug 2
No devices or entities
Failed setup, will retry: An error occurred updating TM19: e=BleakError('esphome-ed6328 [08:D1:F9:ED:63:28]: Ember Travel Mug 2 - C4:DB:D1:2E:C6:A6 is not connected')
```
```
Logger: ember_mug.mug Source: custom_components/ember_mug/coordinator.py:71  integration: Ember Mug ([documentation](https://github.com/sopelj/hass_ember_mug), [issues](https://github.com/sopelj/hass_ember_mug/issues))  First occurred: 2:02:03 PM (2 occurrences)  Last logged: 2:02:09 PM
Failed to subscribe to state attr: Not connected
```
```
Logger: homeassistant.config_entries Source: config_entries.py:635  First occurred: 1:58:05 PM (2 occurrences)  Last logged: 1:59:59 PM
Error setting up entry Ember Travel Mug 2 for ember_mug
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 584, in bluetooth_device_connect
    await connect_future
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/__init__.py", line 106, in async_setup_entry
    await mug_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 308, in async_config_entry_first_refresh
    if await self.__wrap_async_setup():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 321, in __wrap_async_setup
    await self._async_setup()
  File "/config/custom_components/ember_mug/coordinator.py", line 71, in _async_setup
    await self.mug.update_initial()
  File "/usr/local/lib/python3.12/site-packages/ember_mug/mug.py", line 400, in update_initial
    return await self._update_multiple(INITIAL_ATTRS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ember_mug/mug.py", line 411, in _update_multiple
    await self._ensure_connection()
  File "/usr/local/lib/python3.12/site-packages/ember_mug/mug.py", line 150, in _ensure_connection
    client = await establish_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 311, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 78, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 299, in connect
    await self._client.bluetooth_device_connect(
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 600, in bluetooth_device_connect
    not await self._bluetooth_device_disconnect_guard_timeout(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 625, in _bluetooth_device_disconnect_guard_timeout
    await self.bluetooth_device_disconnect(address, timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 676, in bluetooth_device_disconnect
    await self._bluetooth_device_request(
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 730, in _bluetooth_device_request
    [response] = await self._get_connection().send_messages_await_response_complex(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aioesphomeapi/connection.py", line 833, in aioesphomeapi.connection.APIConnection.send_messages_await_response_complex
asyncio.exceptions.CancelledError
```

**Integration Debug:**
```
2024-11-10 14:05:25.004 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (7) - Data: bytearray(b'\x07').
2024-11-10 14:05:31.405 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (7) - Data: bytearray(b'\x07').
2024-11-10 14:05:31.491 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Updating
2024-11-10 14:05:31.491 DEBUG (MainThread) [ember_mug.mug] Updating the following attributes: {'battery_voltage', 'liquid_level', 'name', 'temperature_unit', 'volume_level', 'liquid_state', 'battery', 'current_temp', 'target_temp'}
2024-11-10 14:05:31.623 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540011-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'')'
2024-11-10 14:05:31.706 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540005-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x0e')'
2024-11-10 14:05:31.919 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540001-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'ROSS')'
2024-11-10 14:05:32.044 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540004-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x00')'
2024-11-10 14:05:32.215 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540009-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x02')'
2024-11-10 14:05:32.328 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540008-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x06')'
2024-11-10 14:05:32.443 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540007-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x0c\x01\xdb\x11\x03\x02\x01\x00')'
2024-11-10 14:05:32.626 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540002-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'j\x18')'
2024-11-10 14:05:32.739 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540003-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'j\x18')'
2024-11-10 14:05:32.739 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f82f80b1d90>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f83068c34c0>}
2024-11-10 14:05:32.739 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2024-11-10 14:05:32.740 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-travel-mug-c6fca91ae101 data
2024-11-10 14:05:32.741 DEBUG (MainThread) [ember_mug.mug] Attributes updated: [Change(attr='liquid_level', old_value=20, new_value=14)]
2024-11-10 14:05:32.742 DEBUG (MainThread) [custom_components.ember_mug.coordinator] [Full Update] Changed: [Change(attr='liquid_level', old_value=20, new_value=14)]
2024-11-10 14:05:32.743 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching ember-travel-mug-c6fca91ae101 data in 1.251 seconds (success: True)
2024-11-10 14:05:33.555 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (3) - Data: bytearray(b'\x03').
2024-11-10 14:05:33.555 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f82f80b1d90>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f83068c34c0>}
2024-11-10 14:05:33.556 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2024-11-10 14:05:33.556 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-travel-mug-c6fca91ae101 data
2024-11-10 14:05:36.948 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (7) - Data: bytearray(b'\x07').
2024-11-10 14:05:39.794 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (2) - Data: bytearray(b'\x02').
2024-11-10 14:05:39.794 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f82f80b1d90>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f83068c34c0>}
2024-11-10 14:05:39.794 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2024-11-10 14:05:39.794 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-travel-mug-c6fca91ae101 data
2024-11-10 14:05:43.380 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (7) - Data: bytearray(b'\x07').
2024-11-10 14:05:54.430 DEBUG (MainThread) [ember_mug.mug] Push event received from TM19 (7) - Data: bytearray(b'\x07').
2024-11-10 14:05:54.492 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Updating
2024-11-10 14:05:54.492 DEBUG (MainThread) [ember_mug.mug] Updating queued attributes: {'battery', 'liquid_level'}
2024-11-10 14:05:54.643 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540007-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x0c\x01\xcd\x11\x03\x02\x01\x00')'
2024-11-10 14:05:54.744 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540005-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x06')'
2024-11-10 14:05:54.744 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f82f80b1d90>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f83068c34c0>}
2024-11-10 14:05:54.744 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2024-11-10 14:05:54.745 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-travel-mug-c6fca91ae101 data
2024-11-10 14:05:54.746 DEBUG (MainThread) [custom_components.ember_mug.coordinator] [Partial Update] Changed: [Change(attr='liquid_level', old_value=14, new_value=6)]
2024-11-10 14:05:54.747 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching ember-travel-mug-c6fca91ae101 data in 0.255 seconds (success: True)
```

**Comment by sopelj** [comment]
Hi! Thanks for all the information. That's very helpful.

So, just to understand. Does it not connect at all now? Because, except for the one error, the logs seem to show it correctly connecting and fetching data. Did you remove the device from Home Assistant when you factory reset and re-added it? After pairing it with your phone did you disable Bluetooth or unpair it to ensure it is not trying to connect to the mug at the same time the integration is?

Do you have multiple proxies or other Bluetooth devices that might be causing interference?

Are you using both mugs at the same time with Home Assistant?

Thanks!

**Comment by walk0080** [comment]
What I found today is that the new Travel Mug 2 showed up as a new discovered item and it paired OK with Home Assistant (after I had powered off the old mug earlier in the day). Later on I turned the old mug back on and they both seem to work fine at the same time..

To answer your questions in case they are of use to anyone:

I have 3 ESPHome devices w/ BT Proxy, but all of the pairing attempts were in the office within range of only one of them. The other 2 BT Proxies didn't show any log entries for the new mug.

Yes, removed the new mug from HA after factory reset.

Yes, unpaired the new mug from iOS after the initial setup using the iOS Ember App, and then tried pairing w/ HA.

**Comment by sopelj** [comment]
> What I found today is that the new Travel Mug 2 showed up as a new discovered item and it paired OK with Home Assistant (after I had powered off the old mug earlier in the day). Later on I turned the old mug back on and they both seem to work fine at the same time..
> 
> To answer your questions in case they are of use to anyone:
> 
> I have 3 ESPHome devices w/ BT Proxy, but all of the pairing attempts were in the office within range of only one of them. The other 2 BT Proxies didn't show any log entries for the new mug.
> 
> Yes, removed the new mug from HA after factory reset.
> 
> Yes, unpaired the new mug from iOS after the initial setup using the iOS Ember App, and then tried pairing w/ HA.

Thank you! I appreciate the extra information.

You may need to put the mugs into pairing mode in proximity to the other proxies. They may need to be paired individually to certain ones.

**Comment by walk0080** [comment]
> Thank you! I appreciate the extra information.
> 
> You may need to put the mugs into pairing mode in proximity to the other proxies. They may need to be paired individually to certain ones.

Only had to pair once in HA and the mug is connecting to all three ESPHome BT Proxies.

Don't know how seamless the process is, or if the mug times-out after a while and connects to a closer BT Proxy. Have not been watching close enough to tell. But I have noticed that the mug does connect to more than one BT Proxy as the MAC shows up in the logs on multiple devices at different points of time. Either way, it works well enough for my use case - thx for the integration/component and the feedback.
