### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by Royal911** [sopelj/hass-ember-mug-component#62]
* Home Assistant Version (eg. 2023.11):
* Core
2024.12.0
Frontend
20241127.4
* Ember Mug Component Version (eg. 0.8.0):
* 1.2.0
* Which device(s) are you using for Bluetooth (e.g. Bluetooth Dongle / ESPHome Proxy):
Bluetooth Dongle 
### Description

I migrated the HomeAssistant from one server to another . And now the Integration  has no entities 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

### Logs / Errors

If possible/applicable, please enable logging, reproduce the issue and include any related errors below.
This greatly helps with debugging and is much appreciated.
(If you aren't sure how to enable it, please see the [debugging section](https://github.com/sopelj/hass-ember-mug-component#debugging) in the README)

```
LOGS 

 await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/binary_sensor.py", line 92, in async_setup_entry
    MugBinarySensor(coordinator, "battery.on_charging_base"),
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/binary_sensor.py", line 54, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-12-06 15:04:57.286 ERROR (MainThread) [homeassistant.components.light] Error while setting up ember_mug platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/light.py", line 90, in async_setup_entry
    entities = [MugLightEntity(coordinator, "led_colour")]
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-12-06 15:04:57.288 ERROR (MainThread) [homeassistant.components.number] Error while setting up ember_mug platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/number.py", line 85, in async_setup_entry
    MugTargetTempNumberEntity(coordinator, "target_temp"),
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/number.py", line 56, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-12-06 15:04:57.291 ERROR (MainThread) [homeassistant.components.select] Error while setting up ember_mug platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/select.py", line 163, in async_setup_entry
    MugTemperaturePresetSelectEntity(temp_presets, preset_unit, coordinator, "temperature_preset"),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/select.py", line 124, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/select.py", line 60, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-12-06 15:04:57.294 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ember_mug platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/sensor.py", line 204, in async_setup_entry
    EmberMugStateSensor(coordinator, "liquid_state"),
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/sensor.py", line 80, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2024-12-06 15:04:57.297 ERROR (MainThread) [homeassistant.components.switch] Error while setting up ember_mug platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ember_mug/switch.py", line 91, in async_setup_entry
    async_add_entities([MugTemperatureControlEntity(coordinator, "target_temp")])
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/switch.py", line 48, in __init__
    super().__init__(coordinator, device_attr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/entity.py", line 58, in __init__
    self._attr_device_info = coordinator.device_info
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ember_mug/coordinator.py", line 202, in device_info
    model_id=self.data.model_info.model.value,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by Royal911** [comment]
![image](https://github.com/user-attachments/assets/d5246acf-3438-4a89-9e83-455271813a31)

**Comment by sopelj** [comment]
Oh! Sorry about that. I didn't think the model could be `None`. It really shouldn't be... What device do you have? Regardless, it should not crash. I think I fixed it and I pushed a beta build. Would you mind trying with 1.2.1-beta-1? Thanks!

**Comment by srijan** [comment]
I had the same issue.. the beta fixed it for me, thanks.
I have the Ember Mug 2 Stainless Steel (model: CM191407US)

**Comment by dshokouhi** [comment]
Strange I did not see this error but my tumbler was not discovered/added when I updated to the stable version an hour ago. The beta also fixed it for me. Ember Tumbler here.

**Comment by sopelj** [comment]
Ok, thank you very much for the feedback. I created the 1.2.1 release. Hopefully that will prevent this issue and any related ones.

**Comment by Royal911** [comment]
Hello . Just updated to 1.2.1 and all device and entities are back. Thank you
![image](https://github.com/user-attachments/assets/7fb04339-654a-4350-ac2d-7c43073f9dfc)

**Comment by sopelj** [comment]
Awesome, thanks! Sorry about that.
